<?= $this->extend('backend/layout'); ?>

<?= $this->section('content'); ?>
<div class="card">
    <div class="card-body">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, temporibus aliquam sed explicabo debitis suscipit fuga aspernatur doloribus nisi eum laboriosam non aliquid quod dolores nobis distinctio commodi molestiae? Excepturi quaerat neque, sequi nam possimus quas explicabo in at quo corporis, deleniti tempore odio quod provident laudantium, non ullam voluptatem alias adipisci dolore! Maiores repellendus quaerat adipisci ipsa enim incidunt atque corrupti ad. Pariatur quidem at, nesciunt vitae ducimus amet atque quam eaque voluptates molestiae iusto eum libero? Officia repellendus iusto earum debitis aliquam, incidunt dolor, inventore nihil sit ipsa dignissimos nisi temporibus magni pariatur! Accusamus, repellendus nam? Tempore, eligendi cum ipsum, odit quam ut ab quisquam maxime cupiditate similique pariatur. Fugiat, obcaecati accusantium at laborum in nam sequi beatae aspernatur tenetur, eveniet cum doloribus magnam, ad consequuntur provident magni non asperiores dicta dolor ipsam dolorum eos architecto maiores nobis! Obcaecati, laboriosam facere. Veritatis incidunt minus molestiae magni quo recusandae!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, temporibus aliquam sed explicabo debitis suscipit fuga aspernatur doloribus nisi eum laboriosam non aliquid quod dolores nobis distinctio commodi molestiae? Excepturi quaerat neque, sequi nam possimus quas explicabo in at quo corporis, deleniti tempore odio quod provident laudantium, non ullam voluptatem alias adipisci dolore! Maiores repellendus quaerat adipisci ipsa enim incidunt atque corrupti ad. Pariatur quidem at, nesciunt vitae ducimus amet atque quam eaque voluptates molestiae iusto eum libero? Officia repellendus iusto earum debitis aliquam, incidunt dolor, inventore nihil sit ipsa dignissimos nisi temporibus magni pariatur! Accusamus, repellendus nam? Tempore, eligendi cum ipsum, odit quam ut ab quisquam maxime cupiditate similique pariatur. Fugiat, obcaecati accusantium at laborum in nam sequi beatae aspernatur tenetur, eveniet cum doloribus magnam, ad consequuntur provident magni non asperiores dicta dolor ipsam dolorum eos architecto maiores nobis! Obcaecati, laboriosam facere. Veritatis incidunt minus molestiae magni quo recusandae!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, temporibus aliquam sed explicabo debitis suscipit fuga aspernatur doloribus nisi eum laboriosam non aliquid quod dolores nobis distinctio commodi molestiae? Excepturi quaerat neque, sequi nam possimus quas explicabo in at quo corporis, deleniti tempore odio quod provident laudantium, non ullam voluptatem alias adipisci dolore! Maiores repellendus quaerat adipisci ipsa enim incidunt atque corrupti ad. Pariatur quidem at, nesciunt vitae ducimus amet atque quam eaque voluptates molestiae iusto eum libero? Officia repellendus iusto earum debitis aliquam, incidunt dolor, inventore nihil sit ipsa dignissimos nisi temporibus magni pariatur! Accusamus, repellendus nam? Tempore, eligendi cum ipsum, odit quam ut ab quisquam maxime cupiditate similique pariatur. Fugiat, obcaecati accusantium at laborum in nam sequi beatae aspernatur tenetur, eveniet cum doloribus magnam, ad consequuntur provident magni non asperiores dicta dolor ipsam dolorum eos architecto maiores nobis! Obcaecati, laboriosam facere. Veritatis incidunt minus molestiae magni quo recusandae!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, temporibus aliquam sed explicabo debitis suscipit fuga aspernatur doloribus nisi eum laboriosam non aliquid quod dolores nobis distinctio commodi molestiae? Excepturi quaerat neque, sequi nam possimus quas explicabo in at quo corporis, deleniti tempore odio quod provident laudantium, non ullam voluptatem alias adipisci dolore! Maiores repellendus quaerat adipisci ipsa enim incidunt atque corrupti ad. Pariatur quidem at, nesciunt vitae ducimus amet atque quam eaque voluptates molestiae iusto eum libero? Officia repellendus iusto earum debitis aliquam, incidunt dolor, inventore nihil sit ipsa dignissimos nisi temporibus magni pariatur! Accusamus, repellendus nam? Tempore, eligendi cum ipsum, odit quam ut ab quisquam maxime cupiditate similique pariatur. Fugiat, obcaecati accusantium at laborum in nam sequi beatae aspernatur tenetur, eveniet cum doloribus magnam, ad consequuntur provident magni non asperiores dicta dolor ipsam dolorum eos architecto maiores nobis! Obcaecati, laboriosam facere. Veritatis incidunt minus molestiae magni quo recusandae!</p>
    </div>
</div>
<?= $this->endSection(); ?>